package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * AllowanceHasEmployees generated by hbm2java
 */
public class AllowanceHasEmployees  implements java.io.Serializable {


     private Integer allowanceHasEmployeescol;
     private Allowance allowance;
     private Employees employees;
     private String date;
     private Double amount;
     private String isDelete;

    public AllowanceHasEmployees() {
    }

	
    public AllowanceHasEmployees(Allowance allowance, Employees employees) {
        this.allowance = allowance;
        this.employees = employees;
    }
    public AllowanceHasEmployees(Allowance allowance, Employees employees, String date, Double amount, String isDelete) {
       this.allowance = allowance;
       this.employees = employees;
       this.date = date;
       this.amount = amount;
       this.isDelete = isDelete;
    }
   
    public Integer getAllowanceHasEmployeescol() {
        return this.allowanceHasEmployeescol;
    }
    
    public void setAllowanceHasEmployeescol(Integer allowanceHasEmployeescol) {
        this.allowanceHasEmployeescol = allowanceHasEmployeescol;
    }
    public Allowance getAllowance() {
        return this.allowance;
    }
    
    public void setAllowance(Allowance allowance) {
        this.allowance = allowance;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


