package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private Integer idAnswers;
     private Login login;
     private SecurityQuestion securityQuestion;
     private String a1;
     private String a2;
     private String a3;
     private String isDelete;

    public Answers() {
    }

	
    public Answers(Login login, SecurityQuestion securityQuestion) {
        this.login = login;
        this.securityQuestion = securityQuestion;
    }
    public Answers(Login login, SecurityQuestion securityQuestion, String a1, String a2, String a3, String isDelete) {
       this.login = login;
       this.securityQuestion = securityQuestion;
       this.a1 = a1;
       this.a2 = a2;
       this.a3 = a3;
       this.isDelete = isDelete;
    }
   
    public Integer getIdAnswers() {
        return this.idAnswers;
    }
    
    public void setIdAnswers(Integer idAnswers) {
        this.idAnswers = idAnswers;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public SecurityQuestion getSecurityQuestion() {
        return this.securityQuestion;
    }
    
    public void setSecurityQuestion(SecurityQuestion securityQuestion) {
        this.securityQuestion = securityQuestion;
    }
    public String getA1() {
        return this.a1;
    }
    
    public void setA1(String a1) {
        this.a1 = a1;
    }
    public String getA2() {
        return this.a2;
    }
    
    public void setA2(String a2) {
        this.a2 = a2;
    }
    public String getA3() {
        return this.a3;
    }
    
    public void setA3(String a3) {
        this.a3 = a3;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


