package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * EmployeesHasTable generated by hbm2java
 */
public class EmployeesHasTable  implements java.io.Serializable {


     private Integer id;
     private Employees employees;
     private Table table;
     private String status;

    public EmployeesHasTable() {
    }

	
    public EmployeesHasTable(Employees employees, Table table) {
        this.employees = employees;
        this.table = table;
    }
    public EmployeesHasTable(Employees employees, Table table, String status) {
       this.employees = employees;
       this.table = table;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Table getTable() {
        return this.table;
    }
    
    public void setTable(Table table) {
        this.table = table;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


