package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * GrnhasExess generated by hbm2java
 */
public class GrnhasExess  implements java.io.Serializable {


     private Integer idGrnhasExess;
     private RawGrn rawGrn;
     private String exessDate;
     private String exessAmount;
     private String isDelete;

    public GrnhasExess() {
    }

	
    public GrnhasExess(RawGrn rawGrn) {
        this.rawGrn = rawGrn;
    }
    public GrnhasExess(RawGrn rawGrn, String exessDate, String exessAmount, String isDelete) {
       this.rawGrn = rawGrn;
       this.exessDate = exessDate;
       this.exessAmount = exessAmount;
       this.isDelete = isDelete;
    }
   
    public Integer getIdGrnhasExess() {
        return this.idGrnhasExess;
    }
    
    public void setIdGrnhasExess(Integer idGrnhasExess) {
        this.idGrnhasExess = idGrnhasExess;
    }
    public RawGrn getRawGrn() {
        return this.rawGrn;
    }
    
    public void setRawGrn(RawGrn rawGrn) {
        this.rawGrn = rawGrn;
    }
    public String getExessDate() {
        return this.exessDate;
    }
    
    public void setExessDate(String exessDate) {
        this.exessDate = exessDate;
    }
    public String getExessAmount() {
        return this.exessAmount;
    }
    
    public void setExessAmount(String exessAmount) {
        this.exessAmount = exessAmount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


