package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCreditCard generated by hbm2java
 */
public class InvoiceHasCreditCard  implements java.io.Serializable {


     private Integer idInvoiceHasCreditCard;
     private Invoice invoice;
     private String last4digits;
     private Double paidAmount;
     private String isDelete;

    public InvoiceHasCreditCard() {
    }

	
    public InvoiceHasCreditCard(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoiceHasCreditCard(Invoice invoice, String last4digits, Double paidAmount, String isDelete) {
       this.invoice = invoice;
       this.last4digits = last4digits;
       this.paidAmount = paidAmount;
       this.isDelete = isDelete;
    }
   
    public Integer getIdInvoiceHasCreditCard() {
        return this.idInvoiceHasCreditCard;
    }
    
    public void setIdInvoiceHasCreditCard(Integer idInvoiceHasCreditCard) {
        this.idInvoiceHasCreditCard = idInvoiceHasCreditCard;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getLast4digits() {
        return this.last4digits;
    }
    
    public void setLast4digits(String last4digits) {
        this.last4digits = last4digits;
    }
    public Double getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(Double paidAmount) {
        this.paidAmount = paidAmount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


