package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * InvoicePaymentInfo generated by hbm2java
 */
public class InvoicePaymentInfo  implements java.io.Serializable {


     private Integer idInvoicePaymentInfo;
     private Invoice invoice;
     private String cashTenderd;
     private String cashBalance;
     private String isDelete;

    public InvoicePaymentInfo() {
    }

	
    public InvoicePaymentInfo(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoicePaymentInfo(Invoice invoice, String cashTenderd, String cashBalance, String isDelete) {
       this.invoice = invoice;
       this.cashTenderd = cashTenderd;
       this.cashBalance = cashBalance;
       this.isDelete = isDelete;
    }
   
    public Integer getIdInvoicePaymentInfo() {
        return this.idInvoicePaymentInfo;
    }
    
    public void setIdInvoicePaymentInfo(Integer idInvoicePaymentInfo) {
        this.idInvoicePaymentInfo = idInvoicePaymentInfo;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getCashTenderd() {
        return this.cashTenderd;
    }
    
    public void setCashTenderd(String cashTenderd) {
        this.cashTenderd = cashTenderd;
    }
    public String getCashBalance() {
        return this.cashBalance;
    }
    
    public void setCashBalance(String cashBalance) {
        this.cashBalance = cashBalance;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


