package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * InvoiceCommissons generated by hbm2java
 */
public class InvoiceCommissons  implements java.io.Serializable {


     private Integer idInvoiceCommis;
     private Employees employees;
     private Invoice invoice;
     private RawItems rawItems;
     private Double commAmount;
     private String isDelete;
     private String paidDate;

    public InvoiceCommissons() {
    }

	
    public InvoiceCommissons(Employees employees, Invoice invoice, RawItems rawItems) {
        this.employees = employees;
        this.invoice = invoice;
        this.rawItems = rawItems;
    }
    public InvoiceCommissons(Employees employees, Invoice invoice, RawItems rawItems, Double commAmount, String isDelete, String paidDate) {
       this.employees = employees;
       this.invoice = invoice;
       this.rawItems = rawItems;
       this.commAmount = commAmount;
       this.isDelete = isDelete;
       this.paidDate = paidDate;
    }
   
    public Integer getIdInvoiceCommis() {
        return this.idInvoiceCommis;
    }
    
    public void setIdInvoiceCommis(Integer idInvoiceCommis) {
        this.idInvoiceCommis = idInvoiceCommis;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public RawItems getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public Double getCommAmount() {
        return this.commAmount;
    }
    
    public void setCommAmount(Double commAmount) {
        this.commAmount = commAmount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getPaidDate() {
        return this.paidDate;
    }
    
    public void setPaidDate(String paidDate) {
        this.paidDate = paidDate;
    }




}


