package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * LeaveManagement generated by hbm2java
 */
public class LeaveManagement  implements java.io.Serializable {


     private int idLeaveManagement;
     private Employees employees;
     private String requestDate;
     private String leaveStart;
     private String leaveEnd;
     private String noOfDays;
     private String approveBy;
     private String isDelete;

    public LeaveManagement() {
    }

	
    public LeaveManagement(int idLeaveManagement, Employees employees) {
        this.idLeaveManagement = idLeaveManagement;
        this.employees = employees;
    }
    public LeaveManagement(int idLeaveManagement, Employees employees, String requestDate, String leaveStart, String leaveEnd, String noOfDays, String approveBy, String isDelete) {
       this.idLeaveManagement = idLeaveManagement;
       this.employees = employees;
       this.requestDate = requestDate;
       this.leaveStart = leaveStart;
       this.leaveEnd = leaveEnd;
       this.noOfDays = noOfDays;
       this.approveBy = approveBy;
       this.isDelete = isDelete;
    }
   
    public int getIdLeaveManagement() {
        return this.idLeaveManagement;
    }
    
    public void setIdLeaveManagement(int idLeaveManagement) {
        this.idLeaveManagement = idLeaveManagement;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(String requestDate) {
        this.requestDate = requestDate;
    }
    public String getLeaveStart() {
        return this.leaveStart;
    }
    
    public void setLeaveStart(String leaveStart) {
        this.leaveStart = leaveStart;
    }
    public String getLeaveEnd() {
        return this.leaveEnd;
    }
    
    public void setLeaveEnd(String leaveEnd) {
        this.leaveEnd = leaveEnd;
    }
    public String getNoOfDays() {
        return this.noOfDays;
    }
    
    public void setNoOfDays(String noOfDays) {
        this.noOfDays = noOfDays;
    }
    public String getApproveBy() {
        return this.approveBy;
    }
    
    public void setApproveBy(String approveBy) {
        this.approveBy = approveBy;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


