package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus  implements java.io.Serializable {


     private Integer idOrderStatus;
     private Orders orders;
     private String status;
     private String isDelete;

    public OrderStatus() {
    }

	
    public OrderStatus(Orders orders) {
        this.orders = orders;
    }
    public OrderStatus(Orders orders, String status, String isDelete) {
       this.orders = orders;
       this.status = status;
       this.isDelete = isDelete;
    }
   
    public Integer getIdOrderStatus() {
        return this.idOrderStatus;
    }
    
    public void setIdOrderStatus(Integer idOrderStatus) {
        this.idOrderStatus = idOrderStatus;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


