package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * OrderItems generated by hbm2java
 */
public class OrderItems  implements java.io.Serializable {


     private Integer idOrderItems;
     private Orders orders;
     private RawItems rawItems;
     private Double qty;
     private Double unitPrice;
     private Double netTotalOrdersItem;
     private String isDelete;

    public OrderItems() {
    }

	
    public OrderItems(Orders orders, RawItems rawItems) {
        this.orders = orders;
        this.rawItems = rawItems;
    }
    public OrderItems(Orders orders, RawItems rawItems, Double qty, Double unitPrice, Double netTotalOrdersItem, String isDelete) {
       this.orders = orders;
       this.rawItems = rawItems;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.netTotalOrdersItem = netTotalOrdersItem;
       this.isDelete = isDelete;
    }
   
    public Integer getIdOrderItems() {
        return this.idOrderItems;
    }
    
    public void setIdOrderItems(Integer idOrderItems) {
        this.idOrderItems = idOrderItems;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public RawItems getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getNetTotalOrdersItem() {
        return this.netTotalOrdersItem;
    }
    
    public void setNetTotalOrdersItem(Double netTotalOrdersItem) {
        this.netTotalOrdersItem = netTotalOrdersItem;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


