package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private Integer idpayments;
     private Employees employees;
     private String description;
     private String date;
     private Double amount;

    public Payments() {
    }

	
    public Payments(Employees employees) {
        this.employees = employees;
    }
    public Payments(Employees employees, String description, String date, Double amount) {
       this.employees = employees;
       this.description = description;
       this.date = date;
       this.amount = amount;
    }
   
    public Integer getIdpayments() {
        return this.idpayments;
    }
    
    public void setIdpayments(Integer idpayments) {
        this.idpayments = idpayments;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


