package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Promotion generated by hbm2java
 */
public class Promotion  implements java.io.Serializable {


     private Integer idPromotion;
     private String promotionCode;
     private String promoStartDate;
     private String promoEndDate;
     private Double discountAmountPresent;
     private Double discountAmountRs;
     private String isDelete;
     private String maxDiscountAmount;
     private String promotionDuration;
     private Set promotionItemses = new HashSet(0);

    public Promotion() {
    }

    public Promotion(String promotionCode, String promoStartDate, String promoEndDate, Double discountAmountPresent, Double discountAmountRs, String isDelete, String maxDiscountAmount, String promotionDuration, Set promotionItemses) {
       this.promotionCode = promotionCode;
       this.promoStartDate = promoStartDate;
       this.promoEndDate = promoEndDate;
       this.discountAmountPresent = discountAmountPresent;
       this.discountAmountRs = discountAmountRs;
       this.isDelete = isDelete;
       this.maxDiscountAmount = maxDiscountAmount;
       this.promotionDuration = promotionDuration;
       this.promotionItemses = promotionItemses;
    }
   
    public Integer getIdPromotion() {
        return this.idPromotion;
    }
    
    public void setIdPromotion(Integer idPromotion) {
        this.idPromotion = idPromotion;
    }
    public String getPromotionCode() {
        return this.promotionCode;
    }
    
    public void setPromotionCode(String promotionCode) {
        this.promotionCode = promotionCode;
    }
    public String getPromoStartDate() {
        return this.promoStartDate;
    }
    
    public void setPromoStartDate(String promoStartDate) {
        this.promoStartDate = promoStartDate;
    }
    public String getPromoEndDate() {
        return this.promoEndDate;
    }
    
    public void setPromoEndDate(String promoEndDate) {
        this.promoEndDate = promoEndDate;
    }
    public Double getDiscountAmountPresent() {
        return this.discountAmountPresent;
    }
    
    public void setDiscountAmountPresent(Double discountAmountPresent) {
        this.discountAmountPresent = discountAmountPresent;
    }
    public Double getDiscountAmountRs() {
        return this.discountAmountRs;
    }
    
    public void setDiscountAmountRs(Double discountAmountRs) {
        this.discountAmountRs = discountAmountRs;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getMaxDiscountAmount() {
        return this.maxDiscountAmount;
    }
    
    public void setMaxDiscountAmount(String maxDiscountAmount) {
        this.maxDiscountAmount = maxDiscountAmount;
    }
    public String getPromotionDuration() {
        return this.promotionDuration;
    }
    
    public void setPromotionDuration(String promotionDuration) {
        this.promotionDuration = promotionDuration;
    }
    public Set getPromotionItemses() {
        return this.promotionItemses;
    }
    
    public void setPromotionItemses(Set promotionItemses) {
        this.promotionItemses = promotionItemses;
    }




}


