package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RawGrn generated by hbm2java
 */
public class RawGrn  implements java.io.Serializable {


     private Integer idRawGrn;
     private Supplier supplier;
     private String rawGrnNo;
     private String rawGrnDate;
     private Double subTotal;
     private Double netTotal;
     private String isDelete;
     private Set rowItemGrnPayments = new HashSet(0);
     private Set grnhasExesses = new HashSet(0);
     private Set rowGrnItems = new HashSet(0);

    public RawGrn() {
    }

	
    public RawGrn(Supplier supplier) {
        this.supplier = supplier;
    }
    public RawGrn(Supplier supplier, String rawGrnNo, String rawGrnDate, Double subTotal, Double netTotal, String isDelete, Set rowItemGrnPayments, Set grnhasExesses, Set rowGrnItems) {
       this.supplier = supplier;
       this.rawGrnNo = rawGrnNo;
       this.rawGrnDate = rawGrnDate;
       this.subTotal = subTotal;
       this.netTotal = netTotal;
       this.isDelete = isDelete;
       this.rowItemGrnPayments = rowItemGrnPayments;
       this.grnhasExesses = grnhasExesses;
       this.rowGrnItems = rowGrnItems;
    }
   
    public Integer getIdRawGrn() {
        return this.idRawGrn;
    }
    
    public void setIdRawGrn(Integer idRawGrn) {
        this.idRawGrn = idRawGrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getRawGrnNo() {
        return this.rawGrnNo;
    }
    
    public void setRawGrnNo(String rawGrnNo) {
        this.rawGrnNo = rawGrnNo;
    }
    public String getRawGrnDate() {
        return this.rawGrnDate;
    }
    
    public void setRawGrnDate(String rawGrnDate) {
        this.rawGrnDate = rawGrnDate;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public Set getRowItemGrnPayments() {
        return this.rowItemGrnPayments;
    }
    
    public void setRowItemGrnPayments(Set rowItemGrnPayments) {
        this.rowItemGrnPayments = rowItemGrnPayments;
    }
    public Set getGrnhasExesses() {
        return this.grnhasExesses;
    }
    
    public void setGrnhasExesses(Set grnhasExesses) {
        this.grnhasExesses = grnhasExesses;
    }
    public Set getRowGrnItems() {
        return this.rowGrnItems;
    }
    
    public void setRowGrnItems(Set rowGrnItems) {
        this.rowGrnItems = rowGrnItems;
    }




}


