package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * RawItemStock generated by hbm2java
 */
public class RawItemStock  implements java.io.Serializable {


     private Integer idStock;
     private RawItems rawItems;
     private Double qty;
     private String unit;
     private String isDelete;

    public RawItemStock() {
    }

	
    public RawItemStock(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public RawItemStock(RawItems rawItems, Double qty, String unit, String isDelete) {
       this.rawItems = rawItems;
       this.qty = qty;
       this.unit = unit;
       this.isDelete = isDelete;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public RawItems getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


