package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * RawStockOutgoing generated by hbm2java
 */
public class RawStockOutgoing  implements java.io.Serializable {


     private Integer idRawStockOutgoing;
     private RawItems rawItems;
     private Double qty;
     private String unit;
     private String isDelete;

    public RawStockOutgoing() {
    }

	
    public RawStockOutgoing(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public RawStockOutgoing(RawItems rawItems, Double qty, String unit, String isDelete) {
       this.rawItems = rawItems;
       this.qty = qty;
       this.unit = unit;
       this.isDelete = isDelete;
    }
   
    public Integer getIdRawStockOutgoing() {
        return this.idRawStockOutgoing;
    }
    
    public void setIdRawStockOutgoing(Integer idRawStockOutgoing) {
        this.idRawStockOutgoing = idRawStockOutgoing;
    }
    public RawItems getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


