package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RowItemCatagory generated by hbm2java
 */
public class RowItemCatagory  implements java.io.Serializable {


     private Integer idRowItemCatagory;
     private String catagoryName;
     private String catagoryCode;
     private String isDelete;
     private String catoType;
     private Set rawItemses = new HashSet(0);

    public RowItemCatagory() {
    }

    public RowItemCatagory(String catagoryName, String catagoryCode, String isDelete, String catoType, Set rawItemses) {
       this.catagoryName = catagoryName;
       this.catagoryCode = catagoryCode;
       this.isDelete = isDelete;
       this.catoType = catoType;
       this.rawItemses = rawItemses;
    }
   
    public Integer getIdRowItemCatagory() {
        return this.idRowItemCatagory;
    }
    
    public void setIdRowItemCatagory(Integer idRowItemCatagory) {
        this.idRowItemCatagory = idRowItemCatagory;
    }
    public String getCatagoryName() {
        return this.catagoryName;
    }
    
    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }
    public String getCatagoryCode() {
        return this.catagoryCode;
    }
    
    public void setCatagoryCode(String catagoryCode) {
        this.catagoryCode = catagoryCode;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getCatoType() {
        return this.catoType;
    }
    
    public void setCatoType(String catoType) {
        this.catoType = catoType;
    }
    public Set getRawItemses() {
        return this.rawItemses;
    }
    
    public void setRawItemses(Set rawItemses) {
        this.rawItemses = rawItemses;
    }




}


