package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * RowItemGrnPayment generated by hbm2java
 */
public class RowItemGrnPayment  implements java.io.Serializable {


     private Integer idRowItemGrnPayment;
     private RawGrn rawGrn;
     private Supplier supplier;
     private String rowItemGrnPayDate;
     private Double rowItemGrnPayAmount;
     private String rowItemGrnPayType;
     private String isDelete;

    public RowItemGrnPayment() {
    }

	
    public RowItemGrnPayment(RawGrn rawGrn, Supplier supplier) {
        this.rawGrn = rawGrn;
        this.supplier = supplier;
    }
    public RowItemGrnPayment(RawGrn rawGrn, Supplier supplier, String rowItemGrnPayDate, Double rowItemGrnPayAmount, String rowItemGrnPayType, String isDelete) {
       this.rawGrn = rawGrn;
       this.supplier = supplier;
       this.rowItemGrnPayDate = rowItemGrnPayDate;
       this.rowItemGrnPayAmount = rowItemGrnPayAmount;
       this.rowItemGrnPayType = rowItemGrnPayType;
       this.isDelete = isDelete;
    }
   
    public Integer getIdRowItemGrnPayment() {
        return this.idRowItemGrnPayment;
    }
    
    public void setIdRowItemGrnPayment(Integer idRowItemGrnPayment) {
        this.idRowItemGrnPayment = idRowItemGrnPayment;
    }
    public RawGrn getRawGrn() {
        return this.rawGrn;
    }
    
    public void setRawGrn(RawGrn rawGrn) {
        this.rawGrn = rawGrn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getRowItemGrnPayDate() {
        return this.rowItemGrnPayDate;
    }
    
    public void setRowItemGrnPayDate(String rowItemGrnPayDate) {
        this.rowItemGrnPayDate = rowItemGrnPayDate;
    }
    public Double getRowItemGrnPayAmount() {
        return this.rowItemGrnPayAmount;
    }
    
    public void setRowItemGrnPayAmount(Double rowItemGrnPayAmount) {
        this.rowItemGrnPayAmount = rowItemGrnPayAmount;
    }
    public String getRowItemGrnPayType() {
        return this.rowItemGrnPayType;
    }
    
    public void setRowItemGrnPayType(String rowItemGrnPayType) {
        this.rowItemGrnPayType = rowItemGrnPayType;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


