package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * Salary generated by hbm2java
 */
public class Salary  implements java.io.Serializable {


     private Integer idSalary;
     private Employees employees;
     private String date;
     private Double totalAllowance;
     private Double totalDeductions;
     private Double etf;
     private Double epf;
     private Double totalPayments;
     private Double basicSalary;
     private Double netTotal;
     private String isDelete;
     private String serviceCharge;

    public Salary() {
    }

	
    public Salary(Employees employees) {
        this.employees = employees;
    }
    public Salary(Employees employees, String date, Double totalAllowance, Double totalDeductions, Double etf, Double epf, Double totalPayments, Double basicSalary, Double netTotal, String isDelete, String serviceCharge) {
       this.employees = employees;
       this.date = date;
       this.totalAllowance = totalAllowance;
       this.totalDeductions = totalDeductions;
       this.etf = etf;
       this.epf = epf;
       this.totalPayments = totalPayments;
       this.basicSalary = basicSalary;
       this.netTotal = netTotal;
       this.isDelete = isDelete;
       this.serviceCharge = serviceCharge;
    }
   
    public Integer getIdSalary() {
        return this.idSalary;
    }
    
    public void setIdSalary(Integer idSalary) {
        this.idSalary = idSalary;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getTotalAllowance() {
        return this.totalAllowance;
    }
    
    public void setTotalAllowance(Double totalAllowance) {
        this.totalAllowance = totalAllowance;
    }
    public Double getTotalDeductions() {
        return this.totalDeductions;
    }
    
    public void setTotalDeductions(Double totalDeductions) {
        this.totalDeductions = totalDeductions;
    }
    public Double getEtf() {
        return this.etf;
    }
    
    public void setEtf(Double etf) {
        this.etf = etf;
    }
    public Double getEpf() {
        return this.epf;
    }
    
    public void setEpf(Double epf) {
        this.epf = epf;
    }
    public Double getTotalPayments() {
        return this.totalPayments;
    }
    
    public void setTotalPayments(Double totalPayments) {
        this.totalPayments = totalPayments;
    }
    public Double getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(Double basicSalary) {
        this.basicSalary = basicSalary;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getServiceCharge() {
        return this.serviceCharge;
    }
    
    public void setServiceCharge(String serviceCharge) {
        this.serviceCharge = serviceCharge;
    }




}


