package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * ServiceCharge generated by hbm2java
 */
public class ServiceCharge  implements java.io.Serializable {


     private Integer idServiceCharge;
     private Invoice invoice;
     private String serviceChargeDate;
     private Double amount;
     private String isDelete;

    public ServiceCharge() {
    }

	
    public ServiceCharge(Invoice invoice) {
        this.invoice = invoice;
    }
    public ServiceCharge(Invoice invoice, String serviceChargeDate, Double amount, String isDelete) {
       this.invoice = invoice;
       this.serviceChargeDate = serviceChargeDate;
       this.amount = amount;
       this.isDelete = isDelete;
    }
   
    public Integer getIdServiceCharge() {
        return this.idServiceCharge;
    }
    
    public void setIdServiceCharge(Integer idServiceCharge) {
        this.idServiceCharge = idServiceCharge;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getServiceChargeDate() {
        return this.serviceChargeDate;
    }
    
    public void setServiceChargeDate(String serviceChargeDate) {
        this.serviceChargeDate = serviceChargeDate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


