package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * ServiceChargeEmployee generated by hbm2java
 */
public class ServiceChargeEmployee  implements java.io.Serializable {


     private Integer idServiceCharge;
     private Employees employees;
     private Invoice invoice;
     private InvoiceItems invoiceItems;
     private String serviceChargeDate;
     private Double amount;
     private String isDelete;

    public ServiceChargeEmployee() {
    }

	
    public ServiceChargeEmployee(Employees employees, Invoice invoice, InvoiceItems invoiceItems) {
        this.employees = employees;
        this.invoice = invoice;
        this.invoiceItems = invoiceItems;
    }
    public ServiceChargeEmployee(Employees employees, Invoice invoice, InvoiceItems invoiceItems, String serviceChargeDate, Double amount, String isDelete) {
       this.employees = employees;
       this.invoice = invoice;
       this.invoiceItems = invoiceItems;
       this.serviceChargeDate = serviceChargeDate;
       this.amount = amount;
       this.isDelete = isDelete;
    }
   
    public Integer getIdServiceCharge() {
        return this.idServiceCharge;
    }
    
    public void setIdServiceCharge(Integer idServiceCharge) {
        this.idServiceCharge = idServiceCharge;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoiceItems getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(InvoiceItems invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public String getServiceChargeDate() {
        return this.serviceChargeDate;
    }
    
    public void setServiceChargeDate(String serviceChargeDate) {
        this.serviceChargeDate = serviceChargeDate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


