package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierReturn generated by hbm2java
 */
public class SupplierReturn  implements java.io.Serializable {


     private Integer idSupplierReturn;
     private RowGrnItem rowGrnItem;
     private Supplier supplier;
     private String returnDate;
     private Double qty;
     private String description;
     private String isDelete;
     private Set supReturnTermses = new HashSet(0);

    public SupplierReturn() {
    }

	
    public SupplierReturn(RowGrnItem rowGrnItem, Supplier supplier) {
        this.rowGrnItem = rowGrnItem;
        this.supplier = supplier;
    }
    public SupplierReturn(RowGrnItem rowGrnItem, Supplier supplier, String returnDate, Double qty, String description, String isDelete, Set supReturnTermses) {
       this.rowGrnItem = rowGrnItem;
       this.supplier = supplier;
       this.returnDate = returnDate;
       this.qty = qty;
       this.description = description;
       this.isDelete = isDelete;
       this.supReturnTermses = supReturnTermses;
    }
   
    public Integer getIdSupplierReturn() {
        return this.idSupplierReturn;
    }
    
    public void setIdSupplierReturn(Integer idSupplierReturn) {
        this.idSupplierReturn = idSupplierReturn;
    }
    public RowGrnItem getRowGrnItem() {
        return this.rowGrnItem;
    }
    
    public void setRowGrnItem(RowGrnItem rowGrnItem) {
        this.rowGrnItem = rowGrnItem;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(String returnDate) {
        this.returnDate = returnDate;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public Set getSupReturnTermses() {
        return this.supReturnTermses;
    }
    
    public void setSupReturnTermses(Set supReturnTermses) {
        this.supReturnTermses = supReturnTermses;
    }




}


