package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * SupReturnTerms generated by hbm2java
 */
public class SupReturnTerms  implements java.io.Serializable {


     private Integer idSupReturnTerms;
     private SupplierReturn supplierReturn;
     private String returnTerm;
     private String isDelete;

    public SupReturnTerms() {
    }

	
    public SupReturnTerms(SupplierReturn supplierReturn) {
        this.supplierReturn = supplierReturn;
    }
    public SupReturnTerms(SupplierReturn supplierReturn, String returnTerm, String isDelete) {
       this.supplierReturn = supplierReturn;
       this.returnTerm = returnTerm;
       this.isDelete = isDelete;
    }
   
    public Integer getIdSupReturnTerms() {
        return this.idSupReturnTerms;
    }
    
    public void setIdSupReturnTerms(Integer idSupReturnTerms) {
        this.idSupReturnTerms = idSupReturnTerms;
    }
    public SupplierReturn getSupplierReturn() {
        return this.supplierReturn;
    }
    
    public void setSupplierReturn(SupplierReturn supplierReturn) {
        this.supplierReturn = supplierReturn;
    }
    public String getReturnTerm() {
        return this.returnTerm;
    }
    
    public void setReturnTerm(String returnTerm) {
        this.returnTerm = returnTerm;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


