package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Table generated by hbm2java
 */
public class Table  implements java.io.Serializable {


     private Integer idTable;
     private String tableNo;
     private Set employeesHasTables = new HashSet(0);
     private Set invoiceHasTables = new HashSet(0);

    public Table() {
    }

    public Table(String tableNo, Set employeesHasTables, Set invoiceHasTables) {
       this.tableNo = tableNo;
       this.employeesHasTables = employeesHasTables;
       this.invoiceHasTables = invoiceHasTables;
    }
   
    public Integer getIdTable() {
        return this.idTable;
    }
    
    public void setIdTable(Integer idTable) {
        this.idTable = idTable;
    }
    public String getTableNo() {
        return this.tableNo;
    }
    
    public void setTableNo(String tableNo) {
        this.tableNo = tableNo;
    }
    public Set getEmployeesHasTables() {
        return this.employeesHasTables;
    }
    
    public void setEmployeesHasTables(Set employeesHasTables) {
        this.employeesHasTables = employeesHasTables;
    }
    public Set getInvoiceHasTables() {
        return this.invoiceHasTables;
    }
    
    public void setInvoiceHasTables(Set invoiceHasTables) {
        this.invoiceHasTables = invoiceHasTables;
    }




}


