package ORM;
// Generated May 1, 2018 9:49:59 AM by Hibernate Tools 4.3.1



/**
 * TmpemployeesHasJobroals generated by hbm2java
 */
public class TmpemployeesHasJobroals  implements java.io.Serializable {


     private Integer id;
     private Employees employees;
     private Jobroals jobroals;
     private String startDate;
     private String endDate;
     private String isDelete;

    public TmpemployeesHasJobroals() {
    }

	
    public TmpemployeesHasJobroals(Employees employees, Jobroals jobroals) {
        this.employees = employees;
        this.jobroals = jobroals;
    }
    public TmpemployeesHasJobroals(Employees employees, Jobroals jobroals, String startDate, String endDate, String isDelete) {
       this.employees = employees;
       this.jobroals = jobroals;
       this.startDate = startDate;
       this.endDate = endDate;
       this.isDelete = isDelete;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Jobroals getJobroals() {
        return this.jobroals;
    }
    
    public void setJobroals(Jobroals jobroals) {
        this.jobroals = jobroals;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


