/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ItemAndStock;

import ClassPack.DB;
import ClassPack.Excel;
import ClassPack.FoodCodeHolder;
import ClassPack.PoolManager;
import MainMenu.LoginFrame;
import ORM.FoodItemInfo;
import ORM.RawItems;
import com.alee.laf.WebLookAndFeel;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author oditha
 */
public class ViewFoodItemsUdaya extends javax.swing.JFrame {

    /**
     * Creates new form ViewFoodItemsUdaya
     */
    static boolean maximized = true;

    public ViewFoodItemsUdaya() {
        initComponents();
        tableFoodItem.setRowHeight(40);
        maximizeWindow();
        loadItem();
        tableASC();
        tableFoodItem.setComponentPopupMenu(jPopupMenu1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFoodItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("Edit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Food Items");

        txtSearch.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableFoodItem.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        tableFoodItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Food Code", "Item Name", "Item Catagory", "Selling Price"
            }
        ));
        tableFoodItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableFoodItemMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableFoodItem);
        if (tableFoodItem.getColumnModel().getColumnCount() > 0) {
            tableFoodItem.getColumnModel().getColumn(0).setMinWidth(0);
            tableFoodItem.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableFoodItem.getColumnModel().getColumn(0).setMaxWidth(0);
            tableFoodItem.getColumnModel().getColumn(1).setMinWidth(150);
            tableFoodItem.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableFoodItem.getColumnModel().getColumn(1).setMaxWidth(150);
            tableFoodItem.getColumnModel().getColumn(2).setMinWidth(500);
            tableFoodItem.getColumnModel().getColumn(2).setPreferredWidth(500);
            tableFoodItem.getColumnModel().getColumn(2).setMaxWidth(500);
            tableFoodItem.getColumnModel().getColumn(4).setMinWidth(150);
            tableFoodItem.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableFoodItem.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setText("Search Here");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("To Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        //        try {

        //            Session openSession = PoolManager.getSessionFactory().openSession();
        //            Criteria createCriteria = openSession.createCriteria(Item.class);
        //            //createCriteria.add(Restrictions.like("iitemName", "%" + txtSearch.getText() + "%"));
        //
        //            Criterion name = Restrictions.like("iitemName", "%" + txtSearch.getText() + "%");
        //            Criterion active = Restrictions.like("isActive", "Active");
        //            LogicalExpression andExp = Restrictions.and(name, active);
        //            createCriteria.add(andExp);
        //
        //            List<Item> list = createCriteria.list();
        //
        //            DefaultTableModel dtm = (DefaultTableModel) tableItem.getModel();
        //            dtm.setRowCount(0);
        //
        //            for (Item item : list) {
        //                dtm.addRow(new Object[]{item.getIdItem(), item.getItemCode(), item.getIitemName(), item.getCatogory().getCatogoryName(), item.getBrands().getBrandName(), item.getDescriotion()});
        //            }
        //            openSession.close();
        //        } catch (Exception e) {
        //            e.printStackTrace();
        //        }
        DefaultTableModel dtm = (DefaultTableModel) tableFoodItem.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tableFoodItem.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            JasperPrint jp = JasperFillManager.fillReport(LoginFrame.Menu, null, DB.getCon());
            JasperViewer.viewReport(jp, false);
            JasperPrintManager.printReport(jp, false);

        } catch (Exception ex) {
            Logger.getLogger(ViewFoodItemsUdaya.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableFoodItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFoodItemMouseReleased
//        if (evt.getButton() == 3) {
//            jPopupMenu1.show();
//        }
    }//GEN-LAST:event_tableFoodItemMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            JFileChooser fc = new JFileChooser();
            int showDialog = fc.showSaveDialog(null);;
            File sf = fc.getSelectedFile();
            String path = sf.getAbsolutePath();
            path = path.replace('\\', '/');

            Excel.toExcel(tableFoodItem, new File(path + ".xlsx"));
        } catch (Exception ex) {
            Logger.getLogger(ViewFoodItemsUdaya.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        UpdateCode updateCode = new UpdateCode();
        
        updateCode.jLabel1.setText(tableFoodItem.getValueAt(tableFoodItem.getSelectedRow(), 0).toString());
        updateCode.jTextField1.setText(tableFoodItem.getValueAt(tableFoodItem.getSelectedRow(), 1).toString());
        
        updateCode.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        WebLookAndFeel.install();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFoodItemsUdaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableFoodItem;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void maximizeWindow() {

        if (maximized) {

            ViewFoodItemsUdaya.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment gv = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ViewFoodItemsUdaya.this.setMaximizedBounds(gv.getMaximumWindowBounds());
            maximized = true;
        } else {

            setExtendedState(JFrame.NORMAL);
            maximized = false;

        }

    }

    public static void loadItem() {

        try {
            Session openSession = PoolManager.getSessionFactory().openSession();
            Criteria createCriteria = openSession.createCriteria(RawItems.class);
            createCriteria.add(Restrictions.eq("isRow", "NO"));
            createCriteria.add(Restrictions.eq("isDelete", "Active"));

            List<RawItems> list = createCriteria.list();

            DefaultTableModel dtm = (DefaultTableModel) tableFoodItem.getModel();
            dtm.setRowCount(0);

            TreeMap<Integer, FoodCodeHolder> treeMap = new TreeMap<>();

            for (RawItems item : list) {
                //Iterator iterator = item.getRowItemExpireDates().iterator();
                Iterator iterator = item.getFoodItemInfos().iterator();

                FoodCodeHolder fc = new FoodCodeHolder();

                int code = 0;

                if (iterator.hasNext()) {
                    FoodItemInfo next = (FoodItemInfo) iterator.next();

                    code = Integer.parseInt(next.getFoodItemCode());

                    fc.setId(item.getIdRawItems());
                    fc.setFoodcode(code + "");
                    fc.setCategory(item.getRowItemCatagory().getCatagoryName());
                    fc.setItemName(item.getItemName());
                    fc.setSelling(item.getRawItemsSellingPrice() + "");

                    treeMap.put(code, fc);

                }
                //  dtm.addRow(new Object[]{item.getIdRawItems(), item.getItemName(), item.getRowItemCatagory().getCatagoryName(), item.getRawItemsUnitPrice(), item.getRawItemsSellingPrice()});
            }

            for (Map.Entry<Integer, FoodCodeHolder> entry : treeMap.entrySet()) {
                Integer key = entry.getKey();
                FoodCodeHolder value = entry.getValue();

                if (key != 0) {

                    dtm.addRow(new Object[]{
                        value.getId(),
                        value.getFoodcode(),
                        value.getItemName(),
                        value.getCategory(),
                        value.getSelling()

                    });

                }

            }

            openSession.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void tableASC() {

//        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableFoodItem.getModel());
//        tableFoodItem.setRowSorter(sorter);
//        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
//
//        int columnIndexToSort = 1;
//        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
//
//        sorter.setSortKeys(sortKeys);
//        sorter.sort();
    }
}
